<?php

namespace AppBundle\Repository;

/**
 * EventRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EventRepository extends \Doctrine\ORM\EntityRepository
{
    function getMySubmissionsWithObjects($userPrivateKey){
        return $this->createQueryBuilder('e')
            ->leftJoin('AppBundle\Entity\Object','o')
            ->where('o.privateKey = e.privateKeyObject')
            ->andWhere('privateKeyUser is :userId')
            ->setParameter('userId', $userPrivateKey)
            ->getQuery()->getResult();
    }
}
